FROM rocker/ml-verse:4.4.0
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    python3 python3-dev python3-pip \
    bedtools \
    wget \
    git

# Install python packages
 RUN pip install --upgrade pip && pip install --no-cache-dir --ignore-installed \
    jupyterlab \
    bash_kernel \
    jupyterlab-git \
    ipywidgets \
    jupyterlab-fasta \
    ipysheet \
    jupyterlab-horizon-theme \
    jupyterlab-lsp \
    'python-lsp-server[all]' \
    jupyterlab_vim \
    jupyterlab_execute_time \
    jupyterlab-code-formatter \
    jupytext \
    voila \
    jupyter-book \
    black \
    isort \
    dockerspawner \
    ipykernel \
    tensorflow \
    tensorflow-probability \
    scikit-learn \
    scikeras \
    pyfaidx \
    pyBigWig \
    pyliftover \
    scipy \
    sympy \
    matplotlib \
    umap-learn \
    logomaker \
    pysam \
    pandas \
    tqdm \
    plotnine \
    snakemake \
    HTSeq \
    pyGenomeTracks \
    mpl-scatter-density \
    deeptools \
    statsmodels \
    CrossMap \
    matplotlib-venn \
    biopython \
    panel \
    bokeh \
    biotite \
    upsetplot \
    scanpy \
    pympl \
    imageio \
    wordcloud \
    distfit \
    openai \
    xkcdpass \
    bioframe \
    pybigtools \
    opencv-python \
    karyopype \
    bio-gopher \
    fuzzywuzzy \
    ipympl \
    duckdb \
    karyopype \
    seaborn \
    polars \
    datashader \
    holoviews \
    hvplot \
    colorcet \
    lumen \
    geoviews \
    param \
    plotly \
    pygal \
    altair \
    dask \
    icecream \
    cyvcf2 \
    pybedtools \
    multiqc \
    PyVCF3 \
    pyensembl \
    torch \
    torchvision \
    axial-positional-embedding \
    sinkhorn-transformer \
    "jax[cuda12_pip]" \
    transformers \
    git+https://github.com/instadeepai/nucleotide-transformer@main

# Install meme
RUN mkdir /opt/meme

ADD http://meme-suite.org/meme-software/5.4.1/meme-5.4.1.tar.gz /opt/meme

WORKDIR /opt/meme/

RUN tar zxvf meme-5.4.1.tar.gz && rm -fv meme-5.4.1.tar.gz

RUN cd /opt/meme/meme-5.4.1 && \
     ./configure --prefix=/opt  --enable-build-libxml2 --enable-build-libxslt  && \
     make && \
     make install && \
     rm -rfv /opt/meme

ENV PATH="/opt/libexec/meme-5.4.1:/opt/bin:${PATH}"

RUN apt-get update && apt-get install -y libncurses5-dev

# Install regtools
WORKDIR /opt

RUN git clone https://github.com/griffithlab/regtools

RUN cd regtools/ && \
     mkdir build && \
     cd build/ && \
     cmake .. && \
     make

# Add regtools binary to path
ENV PATH="/opt/regtools/build:${PATH}"

# Install samtools
RUN cd /usr/bin && \
     wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 && \
     tar -vxjf samtools-1.17.tar.bz2 && \
     cd samtools-1.17 && \
     ./configure --prefix=/usr/bin/samtools && \
     make && \
     make install

# Add samtools binary to path
ENV PATH="/usr/bin/samtools/bin:${PATH}"

# Install ucsc tools
RUN for i in wigToBigWig bedGraphToBigWig liftOver bigBedToBed bigWigToBedGraph bigWigMerge; do \
     wget -q http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/$i -O /bin/$i ; chmod +x /bin/$i ; done

# Add top level directories to mount on host system
RUN mkdir /zata /data

CMD ["/bin/bash"]
