services:
  code-server:
    # build: .
    image: clarity001/bioinformatics:code-server
    container_name: code-server
    environment:
      - TZ="America/New_York"
      - DEFAULT_WORKSPACE=/home/dev
    volumes:
      - /zata/data/zlab/zusers/$USER:/home/dev/data
      - /zata/zippy/$USER:/home/dev/zata
    restart: unless-stopped
