services:
  code-server:
    # build: .
    image: clarity001/bioinformatics:code-server
    container_name: code-server
    environment:
      - TZ="America/New_York"
      - DEFAULT_WORKSPACE=/config/data
    volumes:
      - ~/.config/code-server/config:/config
      - /zata/data/zlab/zusers/$USER:/config/data
      - /zata/zippy/$USER:/config/zata
    restart: unless-stopped
