services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - TZ="America/New_York"
      - PASSWORD=${WEBGUI_PASSWORD}
      - SUDO_PASSWORD=${SUDOER_PASSWORD}
      - DEFAULT_WORKSPACE=/config/data
    volumes:
      - ~/.config/code-server/config:/config
      - /zata/data/zlab/zusers/ramirezc:/config/data
      - /zata/zippy/ramirezc:/config/zata
    ports:
      - 8443:8443
    restart: unless-stopped
