# Use an Ubuntu base image for compatibility
FROM clarity001/bioinformatics:base

# Install vscode CLI
RUN curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz && \
    tar -xf vscode_cli.tar.gz && \
    mv code /usr/local/bin/ && \
    rm vscode_cli.tar.gz && \
    mkdir -p /home/dev/data && \
    mkdir -p /home/dev/zata

# Set work directory
WORKDIR /home/dev

# Start code-server
CMD ["/bin/bash", "-c", "code tunnel --accept-server-license-terms --no-sleep --name $HOSTNAME"]
