services:
  code-server:
    # build: .
    image: clarity001/bioinformatics:code-server
    working_dir: /data/zusers/$USER
    container_name: code-server
    environment:
      - TZ="America/New_York"
    volumes:
      - /data:/data
      - /zata:/zata
    restart: unless-stopped
