services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - TZ=America/New_York
      - DEFAULT_WORKSPACE=/home/dev
    volumes:
      - /home/$USER/dev:/home/dev
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
