# Base image
FROM ubuntu:22.04

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"

# Install system packages
RUN apt update && apt install -y \
    curl \
    gpg \
    git \
    vim \
    wget \
    cmake \
    bedtools \
    btop

# Install system libraries
RUN apt update && apt install -y \
    python3 python3-pip python3-dev \
    libncurses-dev \
    libbz2-dev \
    liblzma-dev

# Install core Python packages
RUN pip install --upgrade pip && pip install --no-cache-dir \
    # Jupyter 
    jupyterlab \
    bash_kernel \
    jupyterlab-git \
    ipywidgets \
    jupyterlab-fasta \
    ipysheet \
    jupyterlab-horizon-theme \
    jupyterlab-lsp \
    'python-lsp-server[all]' \
    jupyterlab_vim \
    jupyterlab_execute_time \
    jupytext \
    ipykernel \
    # Core bioinformatics packages
    biopython \
    pysam \
    HTSeq \
    pyfaidx \
    pyBigWig \
    pyliftover \
    deeptools \
    PyVCF3 \
    pyfastx \
    pyensembl \
    snakemake \
    scanpy \
    bioframe \
    pybigtools \
    pybedtools \
    gffutils \
    # Data science
    numpy \
    pandas \
    polars \
    scipy \
    matplotlib \
    seaborn \
    scikit-learn \
    plotly \
    # Machine learning
    tensorflow \
    tensorflow-probability \
    torch \
    torchvision \
    jax \
    # Dev tools
    black \
    isort \
    tqdm \
    icecream

# Bash kernel
RUN python3 -m bash_kernel.install

# Install essential bioinformatics tools

## samtools
RUN cd /usr/bin && \
    wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 && \
    tar -vxjf samtools-1.17.tar.bz2 && \
    cd samtools-1.17 && \
    ./configure --prefix=/usr/bin/samtools && \
    make && \
    make install
ENV PATH="/usr/bin/samtools/bin:${PATH}"

## UCSC tools
RUN for i in wigToBigWig bedGraphToBigWig liftOver bigBedToBed bigWigToBedGraph bigWigMerge; do \
    wget -q http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/$i -O /bin/$i ; chmod +x /bin/$i ; done

## MEME
RUN mkdir /opt/meme && \
    cd /opt/meme/ && \
    wget http://meme-suite.org/meme-software/5.4.1/meme-5.4.1.tar.gz && \
    tar zxvf meme-5.4.1.tar.gz && \
    cd meme-5.4.1 && \
    ./configure --prefix=/opt --enable-build-libxml2 --enable-build-libxslt && \
    make && \
    make install && \
    rm -rf /opt/meme
ENV PATH="/opt/libexec/meme-5.4.1:/opt/bin:${PATH}"

## regtools
WORKDIR /opt
RUN git clone https://github.com/griffithlab/regtools && \
    cd regtools/ && \
    mkdir build && \
    cd build/ && \
    cmake .. && \
    make
ENV PATH="/opt/regtools/build:${PATH}"

# Mount points
RUN mkdir -p /data /zata
