# Use an Ubuntu base image for compatibility
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

## Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages
RUN apt update && apt install -y \
    curl \
    gpg \
    git \
    vim \
    wget \
    cmake \
    bedtools

# Install R
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | gpg --dearmor -o /usr/share/keyrings/r-project.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | tee -a /etc/apt/sources.list.d/r-project.list

# Install system libraries
RUN apt update && apt install -y \
    python3 python3-pip python3-dev \
    r-base \
    libncurses-dev \
    libbz2-dev \
    liblzma-dev \
    libgmp-dev \
    libmpfr-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssl-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libcairo2-dev \
    libxt-dev \
    libgit2-dev \
    libglpk-dev \
    libgsl-dev \
    libhdf5-dev \
    libudunits2-dev \
    libgdal-dev

# Install python packages
RUN pip install --upgrade pip && pip install --no-cache-dir \
    jupyterlab \
    bash_kernel \
    jupyterlab-git \
    ipywidgets \
    jupyterlab-fasta \
    ipysheet \
    jupyterlab-horizon-theme \
    jupyterlab-lsp \
    'python-lsp-server[all]' \
    jupyterlab_vim \
    jupyterlab_execute_time \
    jupyterlab-code-formatter \
    jupytext \
    voila \
    jupyter-book \
    black \
    isort \
    dockerspawner \
    ipykernel \
    'tensorflow[and-cuda]' \
    tensorflow-probability \
    scikit-learn \
    scikeras \
    pyfaidx \
    pyBigWig \
    pyliftover \
    scipy \
    sympy \
    matplotlib \
    umap-learn \
    logomaker \
    pysam \
    pandas \
    tqdm \
    plotnine \
    snakemake \
    HTSeq \
    pyGenomeTracks \
    mpl-scatter-density \
    deeptools \
    statsmodels \
    CrossMap \
    matplotlib-venn \
    biopython \
    panel \
    bokeh \
    biotite \
    upsetplot \
    scanpy \
    pympl \
    imageio \
    wordcloud \
    distfit \
    openai \
    xkcdpass \
    bioframe \
    pybigtools \
    opencv-python \
    karyopype \
    bio-gopher \
    fuzzywuzzy \
    ipympl \
    duckdb \
    karyopype \
    seaborn \
    polars \
    datashader \
    holoviews \
    hvplot \
    colorcet \
    lumen \
    geoviews \
    param \
    plotly \
    pygal \
    altair \
    dask \
    icecream \
    cyvcf2 \
    pybedtools \
    multiqc \
    PyVCF3 \
    pyensembl \
    torch \
    torchvision \
    axial-positional-embedding \
    sinkhorn-transformer \
    "jax[cuda12_pip]" \
    transformers \
    git+https://github.com/instadeepai/nucleotide-transformer@main \
    spliceai \
    gffutils \
    pyfastx \
    git+https://github.com/tkzeng/Pangolin.git@main


# Install bash kernel
RUN python3 -m bash_kernel.install

# Intall R packages
RUN R -e "options(warn=2); install.packages(c('tidyverse', 'ape', 'phylotools', 'ggsci', 'ggstatsplot', 'gganimate', 'ggthemes', 'ggrepel', 'ggforce', 'cowplot', 'shiny', 'BiocManager', 'tidytree', 'data.table', 'scales', 'DT', 'pheatmap', 'ggwordcloud', 'wordcloud', 'wordcloud2', 'microplot', 'rmeta', 'plotly', 'devtools', 'ggstar', 'ggnewscale', 'ggalluvial', 'TDbook', 'aplot', 'patchwork', 'igraph', 'ggraph', 'R.utils', 'ggpubr', 'UpSetR', 'ComplexUpset', 'ggVennDiagram', 'IRkernel'))"

RUN R -e "options(warn=2); IRkernel::installspec(user=F)"

RUN R -e "BiocManager::install(c('treeio', 'DESeq2', 'edgeR', 'org.Mm.eg.db', 'org.Hs.eg.db', 'org.Dm.eg.db', 'org.Ce.eg.db', 'BSgenome.Hsapiens.UCSC.hg38', 'BSgenome.Mmusculus.UCSC.mm10', 'DEXSeq', 'phyloseq', 'dada2'))"

RUN R -e 'options(warn=2); devtools::install_github("omarwagih/ggseqlogo")'

RUN R -e "options(warn=2); devtools::install_github('ianmoran11/mmtable2')"

# Install meme
RUN mkdir /opt/meme

ADD http://meme-suite.org/meme-software/5.4.1/meme-5.4.1.tar.gz /opt/meme

WORKDIR /opt/meme/

RUN tar zxvf meme-5.4.1.tar.gz && rm -fv meme-5.4.1.tar.gz

RUN cd /opt/meme/meme-5.4.1 && \
     ./configure --prefix=/opt  --enable-build-libxml2 --enable-build-libxslt  && \
     make && \
     make install && \
     rm -rfv /opt/meme

ENV PATH="/opt/libexec/meme-5.4.1:/opt/bin:${PATH}"

# Install samtools
RUN cd /usr/bin && \
     wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 && \
     tar -vxjf samtools-1.17.tar.bz2 && \
     cd samtools-1.17 && \
     ./configure --prefix=/usr/bin/samtools && \
     make && \
     make install

# Add samtools binary to path
ENV PATH="/usr/bin/samtools/bin:${PATH}"

# Install ucsc tools
RUN for i in wigToBigWig bedGraphToBigWig liftOver bigBedToBed bigWigToBedGraph; do \
     wget -q http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/$i -O /bin/$i ; chmod +x /bin/$i ; done

# Install vscode CLI
RUN curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz && \
    tar -xf vscode_cli.tar.gz && \
    mv code /usr/local/bin/ && \
    rm vscode_cli.tar.gz

# Start code-server
CMD ["code", "tunnel", "--accept-server-license-terms", "--no-sleep", "--server-data-dir", "$HOME/.config/code-server/.vscode", "--extensions-dir", "$HOME/.config/code-server/.vscode-extensions"]

