# Use an Ubuntu base image for compatibility
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install required dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    python3 python3-pip python3-dev \
    libncurses-dev libbz2-dev liblzma-dev \
    vim \
    wget \
    bedtools \
    && rm -rf /var/lib/apt/lists/*

# Install python packages
RUN pip install --upgrade pip && pip install --no-cache-dir "jupyterlab>=4.1.0"

RUN pip install --no-cache-dir --ignore-installed \
    bash_kernel \
    jupyterlab-git \
    ipywidgets \
    jupyterlab-fasta \
    ipysheet \
    jupyterlab-horizon-theme \
    jupyterlab-lsp \
    'python-lsp-server[all]' \
    jupyterlab_vim \
    jupyterlab_execute_time \
    jupyterlab-code-formatter \
    jupytext \
    voila \
    jupyter-book \
    black \
    isort \
    dockerspawner \
    ipykernel \
    tensorflow \
    tensorflow-probability \
    scikit-learn \
    scikeras \
    pyfaidx \
    pyBigWig \
    pyliftover \
    scipy \
    sympy \
    matplotlib \
    umap-learn \
    logomaker \
    pysam \
    pandas \
    tqdm \
    plotnine \
    snakemake \
    HTSeq \
    pyGenomeTracks \
    mpl-scatter-density \
    deeptools \
    statsmodels \
    CrossMap \
    matplotlib-venn \
    biopython \
    panel \
    bokeh \
    biotite \
    upsetplot \
    scanpy \
    pympl \
    imageio \
    wordcloud \
    distfit \
    openai \
    xkcdpass \
    bioframe \
    pybigtools \
    opencv-python \
    karyopype \
    bio-gopher \
    fuzzywuzzy \
    ipympl \
    duckdb \
    karyopype \
    seaborn \
    polars \
    datashader \
    holoviews \
    hvplot \
    colorcet \
    lumen \
    geoviews \
    param \
    plotly \
    pygal \
    altair \
    dask \
    icecream \
    cyvcf2 \
    pybedtools \
    multiqc

# Install bash kernel
RUN python3 -m bash_kernel.install

# Install meme
RUN mkdir /opt/meme

ADD http://meme-suite.org/meme-software/5.4.1/meme-5.4.1.tar.gz /opt/meme

WORKDIR /opt/meme/

RUN tar zxvf meme-5.4.1.tar.gz && rm -fv meme-5.4.1.tar.gz

RUN cd /opt/meme/meme-5.4.1 && \
     ./configure --prefix=/opt  --enable-build-libxml2 --enable-build-libxslt  && \
     make && \
     make install && \
     rm -rfv /opt/meme

ENV PATH="/opt/libexec/meme-5.4.1:/opt/bin:${PATH}"

# Install samtools
RUN cd /usr/bin && \
     wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 && \
     tar -vxjf samtools-1.17.tar.bz2 && \
     cd samtools-1.17 && \
     ./configure --prefix=/usr/bin/samtools && \
     make && \
     make install

# Install ucsc tools
RUN for i in wigToBigWig bedGraphToBigWig liftOver bigBedToBed bigWigToBedGraph; do \
     wget -q http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/$i -O /bin/$i ; chmod +x /bin/$i ; done

# Add samtools binary to path
ENV PATH="/usr/bin/samtools/bin:${PATH}"

# Install vscode CLI
RUN curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz && \
    tar -xf vscode_cli.tar.gz && \
    mv code /usr/local/bin/ && \
    rm vscode_cli.tar.gz

# Set work directory
WORKDIR /config

# Start code-server
CMD ["code", "tunnel", "--accept-server-license-terms", "--no-sleep", "--server-data-dir", "/config/.vscode", "--extensions-dir", "/config/.vscode-extensions"]

