FROM quay.io/biocontainers/kallisto:0.44.0--h7d86c95_2

# Install git and build essentials
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Clone repository and install
RUN git clone https://github.com/signalbash/how_are_we_stranded_here.git && \
    cd how_are_we_stranded_here && \
    pip install .
