FROM lscr.io/linuxserver/code-server:latest

# Install only the necessary system tools
RUN apt-get update && apt-get install -y \
    build-essential \
    bedtools \
    wget \
    libncurses5-dev \
    libbz2-dev \
    liblzma-dev \
    python3-poetry

# Install samtools (since it's commonly needed with bedtools)
RUN cd /usr/bin && \
    wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 && \
    tar -vxjf samtools-1.17.tar.bz2 && \
    cd samtools-1.17 && \
    ./configure --prefix=/usr/bin/samtools && \
    make && \
    make install

ENV PATH="/usr/bin/samtools/bin:${PATH}"

# Create data directories
RUN mkdir /zata /data
