# Base image
FROM ubuntu:22.04

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"

# Install system packages
RUN apt update && apt install -y \
    curl \
    gpg \
    git \
    vim \
    wget \
    cmake \
    bedtools \
    btop

# Install R
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | gpg --dearmor -o /usr/share/keyrings/r-project.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | tee -a /etc/apt/sources.list.d/r-project.list

# Install system libraries
RUN apt update && apt install -y \
    python3 python3-pip python3-dev \
    r-base \
    libncurses-dev \
    libbz2-dev \
    liblzma-dev \
    libgmp-dev \
    libmpfr-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssl-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libcairo2-dev \
    libxt-dev \
    libgit2-dev \
    libglpk-dev \
    libgsl-dev \
    libhdf5-dev \
    libudunits2-dev \
    libgdal-dev

# Install core Python packages
RUN pip install --upgrade pip && pip install --no-cache-dir \
    # Jupyter 
    jupyterlab \
    bash_kernel \
    jupyterlab-git \
    ipywidgets \
    jupyterlab-fasta \
    ipysheet \
    jupyterlab-horizon-theme \
    jupyterlab-lsp \
    'python-lsp-server[all]' \
    jupyterlab_vim \
    jupyterlab_execute_time \
    jupytext \
    ipykernel \
    # Core bioinformatics packages
    biopython \
    pysam \
    HTSeq \
    pyfaidx \
    pyBigWig \
    pyliftover \
    deeptools \
    PyVCF3 \
    pyfastx \
    pyensembl \
    snakemake \
    scanpy \
    bioframe \
    pybigtools \
    pybedtools \
    gffutils \
    # Data science
    numpy \
    pandas \
    polars \
    scipy \
    matplotlib \
    seaborn \
    scikit-learn \
    plotly \
    # Machine learning
    tensorflow \
    tensorflow-probability \
    torch \
    torchvision \
    jax \
    # Dev tools
    black \
    isort \
    tqdm \
    icecream

# Bash kernel
RUN python3 -m bash_kernel.install

# R packages
RUN R -e "options(warn=2); install.packages(c('tidyverse', 'ape', 'phylotools', 'ggsci', 'ggstatsplot', 'gganimate', 'ggthemes', 'ggrepel', 'ggforce', 'cowplot', 'shiny', 'BiocManager', 'tidytree', 'data.table', 'scales', 'DT', 'pheatmap', 'ggwordcloud', 'wordcloud', 'wordcloud2', 'microplot', 'rmeta', 'plotly', 'devtools', 'ggstar', 'ggnewscale', 'ggalluvial', 'TDbook', 'aplot', 'patchwork', 'igraph', 'ggraph', 'R.utils', 'ggpubr', 'UpSetR', 'ComplexUpset', 'ggVennDiagram', 'IRkernel'))"
RUN R -e "options(warn=2); IRkernel::installspec(user=F)"
RUN R -e "BiocManager::install(c('treeio', 'DESeq2', 'edgeR', 'org.Mm.eg.db', 'org.Hs.eg.db', 'org.Dm.eg.db', 'org.Ce.eg.db', 'BSgenome.Hsapiens.UCSC.hg38', 'BSgenome.Mmusculus.UCSC.mm10', 'DEXSeq', 'phyloseq', 'dada2'))"
RUN R -e 'options(warn=2); devtools::install_github("omarwagih/ggseqlogo")'
RUN R -e "options(warn=2); devtools::install_github('ianmoran11/mmtable2')"

# Install essential bioinformatics tools

## samtools
RUN cd /usr/bin && \
    wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 && \
    tar -vxjf samtools-1.17.tar.bz2 && \
    cd samtools-1.17 && \
    ./configure --prefix=/usr/bin/samtools && \
    make && \
    make install
ENV PATH="/usr/bin/samtools/bin:${PATH}"

## UCSC tools
RUN for i in wigToBigWig bedGraphToBigWig liftOver bigBedToBed bigWigToBedGraph bigWigMerge; do \
    wget -q http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/$i -O /bin/$i ; chmod +x /bin/$i ; done

## MEME
RUN mkdir /opt/meme && \
    cd /opt/meme/ && \
    wget http://meme-suite.org/meme-software/5.4.1/meme-5.4.1.tar.gz && \
    tar zxvf meme-5.4.1.tar.gz && \
    cd meme-5.4.1 && \
    ./configure --prefix=/opt --enable-build-libxml2 --enable-build-libxslt && \
    make && \
    make install && \
    rm -rf /opt/meme
ENV PATH="/opt/libexec/meme-5.4.1:/opt/bin:${PATH}"

## regtools
WORKDIR /opt
RUN git clone https://github.com/griffithlab/regtools && \
    cd regtools/ && \
    mkdir build && \
    cd build/ && \
    cmake .. && \
    make
ENV PATH="/opt/regtools/build:${PATH}"

# Mount points
RUN mkdir -p /data /zata
